ALTER TABLE store_settings
ADD COLUMN IF NOT EXISTS printer_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS printer_host VARCHAR(255),
ADD COLUMN IF NOT EXISTS printer_port INTEGER NOT NULL DEFAULT 8008,
ADD COLUMN IF NOT EXISTS printer_device_id VARCHAR(120) NOT NULL DEFAULT 'local_printer',
ADD COLUMN IF NOT EXISTS printer_use_ssl BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS printer_buffer BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE store_settings
DROP CONSTRAINT IF EXISTS chk_store_settings_printer_port;

ALTER TABLE store_settings
ADD CONSTRAINT chk_store_settings_printer_port
CHECK (printer_port BETWEEN 1 AND 65535);
